pipeline{
    agent any
    parameters {
        choice(choices:["TEST","DEV","QA","PRE-POD","PROD"], description: "Which environment to deploy in?", name: "deployEnv")
    }

    stages{
        stage("Demo"){
            steps{
                echo "choice is set to : ${params.deployEnv}"
            }
        }
    }
}